# Generated by Django 3.2.18 on 2023-03-06 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100)),
                ('spotlight', models.BooleanField(default=False)),
                ('alias', models.CharField(blank=True, default=None, max_length=100)),
                ('thumbnail', models.CharField(blank=True, default=None, max_length=400)),
                ('thumbnail_m', models.CharField(blank=True, default=None, max_length=400)),
                ('is_oa', models.BooleanField(default=True)),
                ('is_oa_brand', models.BooleanField(default=False)),
                ('total_follow', models.IntegerField(blank=True, default=None)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200)),
                ('thumbnail', models.CharField(blank=True, default=None, max_length=400)),
                ('isoffical', models.BooleanField(default=True)),
                ('is_indie', models.BooleanField(default=False)),
                ('release_date', models.CharField(blank=True, default=None, max_length=100)),
                ('sort_description', models.TextField(blank=True, default=None)),
                ('released_at', models.IntegerField(blank=True, default=None)),
                ('pr', models.BooleanField(default=False)),
                ('artist_names', models.CharField(blank=True, default=None, max_length=100)),
                ('play_item_mode', models.IntegerField(default=0)),
                ('sub_type', models.IntegerField(default=1)),
                ('uid', models.IntegerField(blank=True, default=None)),
                ('thumbnail_m', models.CharField(blank=True, default=None, max_length=400)),
                ('is_shuffle', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('user_name', models.CharField(default='Zing MP3', max_length=100)),
                ('is_album', models.BooleanField(default=False)),
                ('text_type', models.CharField(default='Playlist', max_length=100)),
                ('is_single', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistOfTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlists')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.topicplaylist')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistOfPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.artists')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlists')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
