# Generated by Django 3.2.18 on 2023-03-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='release_date',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
