# Generated by Django 3.2.18 on 2023-03-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_playlists_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='released_at',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
