# Generated by Django 3.2.18 on 2023-03-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlists_released_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='uid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
