# Generated by Django 3.2.18 on 2023-03-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0004_alter_playlists_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('title', models.CharField(blank=True, default=None, max_length=200)),
                ('alias', models.CharField(blank=True, default=None, max_length=200)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200)),
                ('alias', models.CharField(blank=True, default=None, max_length=200)),
                ('is_offical', models.BooleanField(blank=True, default=True)),
                ('username', models.CharField(blank=True, default=None, max_length=200)),
                ('artist_names', models.CharField(blank=True, default=None, max_length=100)),
                ('is_world_wide', models.BooleanField(blank=True, default=True)),
                ('thumbnail_m', models.CharField(blank=True, default=None, max_length=400)),
                ('thumbnail', models.CharField(blank=True, default=None, max_length=400)),
                ('duration', models.IntegerField(blank=True, default=None)),
                ('streaming_status', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoOfTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.topicvideo')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.videos')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistOfVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.artists')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.videos')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
