# Generated by Django 3.2.18 on 2023-03-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('thumbnail', models.CharField(blank=True, default=None, max_length=400)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200)),
                ('thumbnail', models.CharField(blank=True, default=None, max_length=400)),
                ('thumbnail_h', models.CharField(blank=True, default=None, max_length=400)),
                ('description', models.TextField(blank=True, default=None)),
                ('start_time', models.IntegerField(blank=True, default=None)),
                ('end_time', models.IntegerField(blank=True, default=None)),
                ('has_song_request', models.BooleanField(blank=True, default=None)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Streamings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200)),
                ('thumbnail', models.CharField(blank=True, default=None, max_length=400)),
                ('thumbnail_m', models.CharField(blank=True, default=None, max_length=400)),
                ('thumbnail_v', models.CharField(blank=True, default=None, max_length=400)),
                ('thumbnail_h', models.CharField(blank=True, default=None, max_length=400)),
                ('description', models.TextField(blank=True, default=None)),
                ('status', models.IntegerField(blank=True, default=None)),
                ('type', models.CharField(blank=True, default=None, max_length=100)),
                ('streaming', models.CharField(blank=True, default=None, max_length=400)),
                ('active_users', models.IntegerField(blank=True, default=None)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramOfStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_stream.programs')),
                ('streaming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_stream.streamings')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostOfStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_stream.hosts')),
                ('streaming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_stream.streamings')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
