# Generated by Django 3.2.18 on 2023-03-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0004_alter_playlists_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataArtistDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('cover', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('biography', models.TextField(blank=True, default=None, null=True)),
                ('sort_biography', models.TextField(blank=True, default=None, null=True)),
                ('national', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('birthday', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('real_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.artists')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.dataartistdetail')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
