# Generated by Django 3.2.18 on 2023-04-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtistDetail',
        ),
        migrations.DeleteModel(
            name='DataArtistDetail',
        ),
    ]
