# Generated by Django 3.2.18 on 2023-03-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
