# Generated by Django 3.2.18 on 2023-03-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banners_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
    ]
