# Generated by Django 3.2.18 on 2023-03-26 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongOfTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist_detail.songs')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist_detail.topicsong')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
